  name: SimpleSpawner
  main: xenialdan\SimpleSpawner\Loader
  version: 1.3.1
  api: ['*', '3.0.0-ALPHA4', '3.0.0-ALPHA5', '3.0.0-ALPHA6']
  load: POSTWORLD
  authors: [XenialDan]
  prefix: "SimpleSpawner by XenialDan"
  permissions:
    simplespawner:
      description: Perm for giving spawner
      default: op